/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: BrushDip (https://sketchfab.com/BrushDip)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-computer-sketchfab-weekly-11-mar23-d9931a9aba7c4ea1bc12b2a59dcef16e
Title: 3d computer  - Sketchfab Weekly - 11 Mar'23
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

const ComputerModel = (props) => {
  const { onClick, position, playerPosition } = props;
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/ComputerModel.glb");
  const { actions } = useAnimations(animations, group);

  const interactionRadius = 3; // Interaction distance
  const distance = useRef(Infinity);

  useFrame(() => {
    if (group.current && playerPosition) {
      // Calculate distance from player to model
      distance.current = new THREE.Vector3(...position).distanceTo(
        new THREE.Vector3(...playerPosition)
      );

      // Highlight model if within interaction radius
    }
  });

  return (
    <group
      ref={group}
      {...props}
      name="ComputerModel"
      dispose={null}
      onClick={() => distance.current <= interactionRadius && onClick()}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[Math.PI / 2, 0, 0.033]}>
          <group
            name="4cef7c9d510940d8bf5a9a57aa408b42fbx"
            rotation={[-Math.PI, 0, 0]}
            scale={0.013}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Monitor-A-"
                  position={[5.993, -1.311, 0.887]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.922, 1, 0.858]}
                >
                  <mesh
                    name="Monitor-A-_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Monitor-A-_computer_0"].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Monitor-B-"
                  position={[5.993, -0.946, 0.887]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.94, 1.019, 1.019]}
                >
                  <mesh
                    name="Monitor-B-_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Monitor-B-_computer_0"].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="screen_glass"
                  position={[5.923, 0.01, 0.887]}
                  scale={[0.922, 1, 1]}
                >
                  <mesh
                    name="screen_glass_screen_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.screen_glass_screen_0.geometry}
                    material={materials.screen}
                  />
                </group>
                <group
                  name="Box002"
                  position={[7.197, -10.437, -20.778]}
                  rotation={[0.092, 0, 0]}
                  scale={[1.199, 1, 1]}
                >
                  <mesh
                    name="Box002_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Box002_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Tower"
                  position={[5.991, 15.639, -21.506]}
                  scale={[1.264, 3.46, 3.388]}
                >
                  <mesh
                    name="Tower_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Tower_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="tower-case"
                  position={[5.991, 15.06, -22.123]}
                  scale={[0.229, 4.055, 4.842]}
                >
                  <mesh
                    name="tower-case_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["tower-case_computer_0"].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Tower-Front"
                  position={[4.05, 14.894, -21.506]}
                  scale={[1.003, 3.604, 3.746]}
                >
                  <mesh
                    name="Tower-Front_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Tower-Front_computer_0"].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="base"
                  position={[8.444, 11.264, -21.436]}
                  scale={[1, 1.108, 1]}
                >
                  <mesh
                    name="base__0"
                    castShadow
                    receiveShadow
                    geometry={nodes.base__0.geometry}
                    material={materials.base__0}
                  />
                </group>
                <group
                  name="key"
                  position={[-4.63, -8.141, -18.599]}
                  rotation={[0.179, 0, 0]}
                  scale={1.458}
                >
                  <mesh
                    name="key_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.key_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="key-alt"
                  position={[11.736, -14.913, -19.82]}
                  rotation={[0.179, 0, 0]}
                  scale={1.458}
                >
                  <mesh
                    name="key-alt_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["key-alt_computer_0"].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Key-space"
                  position={[2.518, -14.913, -19.82]}
                  rotation={[0.179, 0, 0]}
                  scale={1.458}
                >
                  <mesh
                    name="Key-space_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Key-space_computer_0"].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Box050"
                  position={[-8.831, -1.124, -16.062]}
                  scale={[0.752, 1, 1]}
                >
                  <mesh
                    name="Box050_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Box050_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group name="Line001" position={[23.122, 18.732, -21.944]}>
                  <mesh
                    name="Line001_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Line001_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Line002"
                  position={[9.388, 38.916, -12.427]}
                  rotation={[-Math.PI / 2, 1.307, -Math.PI]}
                >
                  <mesh
                    name="Line002_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Line002_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Cylinder001"
                  position={[26.975, 27.836, -21.195]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[1.406, 1.406, 2.681]}
                >
                  <mesh
                    name="Cylinder001_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder001_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Cylinder002"
                  position={[20.395, -4.647, -19.52]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[1.406, 1.406, 0.667]}
                >
                  <mesh
                    name="Cylinder002_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder002_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Cylinder003"
                  position={[11.998, 34.628, -17.568]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[1.406, 1.406, 0.667]}
                >
                  <mesh
                    name="Cylinder003_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder003_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Cylinder005"
                  position={[26.419, -5.489, -20.985]}
                  rotation={[-Math.PI, 0, 0]}
                  scale={[1.406, 1.406, 0.667]}
                >
                  <group name="Object_39" position={[-0.004, 0, -1.261]}>
                    <mesh
                      name="Cylinder005_computer_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cylinder005_computer_0.geometry}
                      material={materials.computer}
                    />
                  </group>
                </group>
                <group
                  name="Cylinder006"
                  position={[-7.387, -5.489, -20.985]}
                  rotation={[-Math.PI, 0, 0]}
                  scale={[1.406, 1.406, 0.667]}
                >
                  <group name="Object_42" position={[-0.004, 0, -1.261]}>
                    <mesh
                      name="Cylinder006_computer_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cylinder006_computer_0.geometry}
                      material={materials.computer}
                    />
                  </group>
                </group>
                <group
                  name="Monitor-C-"
                  position={[5.682, 25.906, 8.752]}
                  rotation={[-0.331, 0, 0]}
                  scale={[0.936, 1, 1]}
                >
                  <mesh
                    name="Monitor-C-_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Monitor-C-_computer_0"].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Tower-drive-"
                  position={[-6.087, -4.529, -17.012]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.769, 1, 1]}
                >
                  <mesh
                    name="Tower-drive-_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Tower-drive-_computer_0"].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Box056"
                  position={[0.133, 34.921, -17.623]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={[1, 0.667, 1.056]}
                >
                  <group name="Object_49" position={[0.106, 0, -1.666]}>
                    <mesh
                      name="Box056_computer_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Box056_computer_0.geometry}
                      material={materials.computer}
                    />
                  </group>
                </group>
                <group
                  name="Object_51"
                  position={[-3.449, 33.381, -17.623]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={[0.701, 0.468, 0.701]}
                >
                  <group name="Object_52" position={[-0.121, 0, -1.666]}>
                    <mesh
                      name="_computer_0"
                      castShadow
                      receiveShadow
                      geometry={nodes._computer_0.geometry}
                      material={materials.computer}
                    />
                  </group>
                </group>
                <group
                  name="Cylinder007"
                  position={[-1.033, 35.15, -17.63]}
                  rotation={[-Math.PI / 2, 0, -Math.PI]}
                >
                  <mesh
                    name="Cylinder007_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder007_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Cylinder008"
                  position={[1.365, 35.15, -17.63]}
                  rotation={[-Math.PI / 2, 0, -Math.PI]}
                >
                  <mesh
                    name="Cylinder008_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder008_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Monitor-D-"
                  position={[12.455, 28.836, -4.974]}
                  rotation={[-1.571, 0, 0]}
                  scale={[0.329, 0.801, 1]}
                >
                  <mesh
                    name="Monitor-D-_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Monitor-D-_computer_0"].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Tower-side"
                  position={[-12.579, 18.098, -16.626]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={[1, 1, 0.133]}
                >
                  <mesh
                    name="Tower-side_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Tower-side_computer_0"].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Tower-nub-"
                  position={[17.033, -2.476, -14.488]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Tower-nub-_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Tower-nub-_computer_0"].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Tower-light-1"
                  position={[17.022, -2.664, -14.495]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Tower-light-1_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Tower-light-1_computer_0"].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Tower-nub-2"
                  position={[16.091, -2.476, -14.488]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Tower-nub-2_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Tower-nub-2_computer_0"].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Tower-nub-3"
                  position={[15.148, -2.476, -14.488]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Tower-nub-3_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Tower-nub-3_computer_0"].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Tower-drive-light"
                  position={[-3.612, -3.255, -16.225]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Tower-drive-light_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Tower-drive-light_computer_0"].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Tower-drive-stub"
                  position={[-3.601, -3.067, -16.218]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Tower-drive-stub_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Tower-drive-stub_computer_0"].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Plane003"
                  position={[-6.087, -8.698, -17.012]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.769, 1, 1]}
                />
                <group
                  name="Tower-drive-button"
                  position={[-8.371, -3.65, -17.641]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[1.462, 1.856, 1]}
                >
                  <mesh
                    name="Tower-drive-button_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Tower-drive-button_computer_0"].geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Tower-light-2"
                  position={[16.089, -3.47, -14.495]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <group name="Object_78" position={[0, 0, -0.807]}>
                    <mesh
                      name="Tower-light-2_computer_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Tower-light-2_computer_0"].geometry}
                      material={materials.computer}
                    />
                  </group>
                </group>
                <group
                  name="Tower-light-3"
                  position={[15.155, -3.47, -14.495]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <group name="Object_81" position={[0, 0, -0.807]}>
                    <mesh
                      name="Tower-light-3_computer_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Tower-light-3_computer_0"].geometry}
                      material={materials.computer}
                    />
                  </group>
                </group>
                <group
                  name="Box060"
                  position={[-8.643, 32.529, -17.609]}
                  rotation={[-Math.PI / 2, 0, -Math.PI]}
                  scale={[1.062, 1.404, 0.67]}
                >
                  <mesh
                    name="Box060_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Box060_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Line003"
                  position={[-8.515, 45.894, -24.066]}
                  rotation={[Math.PI / 2, 1.559, 0]}
                >
                  <mesh
                    name="Line003_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Line003_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Cylinder015"
                  position={[21.179, 33.792, -16.37]}
                  rotation={[-Math.PI / 2, 0, -Math.PI]}
                  scale={[0.793, 0.793, 0.356]}
                >
                  <mesh
                    name="Cylinder015_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder015_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Cylinder016"
                  position={[19.68, 33.792, -16.37]}
                  rotation={[-Math.PI / 2, 0, -Math.PI]}
                  scale={[0.793, 0.793, 0.356]}
                >
                  <mesh
                    name="Cylinder016_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder016_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Cylinder017"
                  position={[21.179, 33.792, -17.813]}
                  rotation={[-Math.PI / 2, 0, -Math.PI]}
                  scale={[0.793, 0.793, 0.356]}
                >
                  <mesh
                    name="Cylinder017_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder017_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Cylinder018"
                  position={[19.68, 33.792, -17.813]}
                  rotation={[-Math.PI / 2, 0, -Math.PI]}
                  scale={[0.793, 0.793, 0.356]}
                >
                  <mesh
                    name="Cylinder018_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder018_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Cylinder019"
                  position={[21.179, 33.792, -19.174]}
                  rotation={[-Math.PI / 2, 0, -Math.PI]}
                  scale={[0.793, 0.793, 0.356]}
                >
                  <mesh
                    name="Cylinder019_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder019_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="Cylinder020"
                  position={[19.68, 33.792, -19.174]}
                  rotation={[-Math.PI / 2, 0, -Math.PI]}
                  scale={[0.793, 0.793, 0.356]}
                >
                  <mesh
                    name="Cylinder020_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder020_computer_0.geometry}
                    material={materials.computer}
                  />
                </group>
                <group
                  name="001"
                  position={[-3.449, 33.381, -15.659]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={[0.701, 0.468, 0.701]}
                >
                  <group name="Object_100" position={[-0.121, 0, -1.666]}>
                    <mesh
                      name="001_computer_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["001_computer_0"].geometry}
                      material={materials.computer}
                    />
                  </group>
                </group>
                <group
                  name="tower-On-frame"
                  position={[22.152, 2.177, -12.827]}
                  rotation={[0.807, -0.002, 0.005]}
                  scale={[0.832, 0.845, 0.845]}
                >
                  <mesh
                    name="tower-On-frame_computer_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["tower-On-frame_computer_0"].geometry}
                    material={materials.computer}
                  />
                  <group name="Tower-on" position={[0, 0, 0.427]} scale={0.74}>
                    <mesh
                      name="Tower-on_computer_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Tower-on_computer_0"].geometry}
                      material={materials.computer}
                    />
                  </group>
                </group>
                <group
                  name="Screen001"
                  position={[5.658, 1.643, 0.812]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.923, 0.855, 0.855]}
                >
                  <mesh
                    name="Screen001_animation_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Screen001_animation_0.geometry}
                    material={materials.animation}
                  >
                    
                  </mesh>
                </group>
                
                <group
                  name="006"
                  position={[16.494, 33.381, -17.776]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={[0.701, 0.468, 0.701]}
                >
                  <group name="Object_518" position={[-0.121, 0, -1.666]}>
                    <mesh
                      name="006_computer_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["006_computer_0"].geometry}
                      material={materials.computer}
                    />
                  </group>
                </group>
                <group
                  name="007"
                  position={[16.494, 33.381, -19.056]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={[0.701, 0.468, 0.701]}
                >
                  <group name="Object_521" position={[-0.121, 0, -1.666]}>
                    <mesh
                      name="007_computer_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["007_computer_0"].geometry}
                      material={materials.computer}
                    />
                  </group>
                </group>
                <group
                  name="008"
                  position={[16.494, 33.381, -16.592]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={[0.701, 0.468, 0.701]}
                >
                  <group name="Object_524" position={[-0.121, 0, -1.666]}>
                    <mesh
                      name="008_computer_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["008_computer_0"].geometry}
                      material={materials.computer}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/ComputerModel.glb");

export default ComputerModel;
