/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const GrassBlock = (props) => {
  const { nodes, materials } = useGLTF("/models/grossssssss.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Small_Grass.geometry}
        material={materials["grass.001"]}
      />
    </group>
  );
};

useGLTF.preload("/models/grossssssss.glb");

export default GrassBlock;
